# Generated by Django 5.1.3 on 2024-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('no_of_guests', models.IntegerField()),
                ('booking_Date', models.DateTimeField()),
            ],
        ),
    ]
